/**********************************************************************
 * Extern for preact
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var preact = {
  "Component": function () {},
  "Fragment": function () {},
  "cloneElement": function () {},
  "createContext": function () {},
  "createElement": function () {},
  "createRef": function () {},
  "h": function () {},
  "hydrate": function () {},
  "isValidElement": function () {},
  "options": {
    "__e": function () {}
  },
  "render": function () {},
  "toChildArray": function () {}
};
preact.Component.prototype = {
  "forceUpdate": function () {},
  "render": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for preact
/**********************************************************************/
